describe('Bloglist ', function () {
  beforeEach(function () {
    cy.request('POST', 'http://localhost:3003/api/testing/reset')
    const user = {
      name: 'Joonas Kinnunen',
      username: 'joonaskinnunen',
      password: 'password'
    }
    cy.request('POST', 'http://localhost:3003/api/users/', user)
    cy.visit('http://localhost:3000')
  })
  it('front page can be opened', function () {
    cy.contains('log in to application')
  })

  it('users-page contains users name', function () {
    cy.get('[data-cy=username]')
      .type('joonaskinnunen')
    cy.get('[data-cy=password]')
      .type('password')
    cy.get('[data-cy=login]')
      .click()
    cy.get('[data-cy=users]')
      .click()
    cy.contains('Joonas Kinnunen')
  })

  it('login works', function () {
    cy.get('[data-cy=username]')
      .type('joonaskinnunen')
    cy.get('[data-cy=password]')
      .type('password')
    cy.get('[data-cy=login]')
      .click()
    cy.contains('Joonas Kinnunen logged in')
  })

  it('new blog creating works', function () {
    cy.get('[data-cy=username]')
      .type('joonaskinnunen')
    cy.get('[data-cy=password]')
      .type('password')
    cy.get('[data-cy=login]')
      .click()
    cy.contains('Joonas Kinnunen logged in')
    cy.contains('create new')
      .click()
    cy.get('[data-cy=title]')
      .type('New Blog')
    cy.get('[data-cy=author]')
      .type('Joonas Kinnunen')
    cy.get('[data-cy=url]')
      .type('http://newblogurl.com')  
    cy.get('[data-cy=newBlog]')
      .click()
    cy.contains('New Blog Joonas Kinnunen')
  })

  it('blog commenting works', function () {
    cy.get('[data-cy=username]')
      .type('joonaskinnunen')
    cy.get('[data-cy=password]')
      .type('password')
    cy.get('[data-cy=login]')
      .click()
    cy.contains('Joonas Kinnunen logged in')
    cy.contains('create new')
      .click()
    cy.get('[data-cy=title]')
      .type('New Blog')
    cy.get('[data-cy=author]')
      .type('Joonas Kinnunen')
    cy.get('[data-cy=url]')
      .type('http://newblogurl.com')  
    cy.get('[data-cy=newBlog]')
      .click()
    cy.contains('New Blog Joonas Kinnunen')
      .click({ force: true })
    cy.get('[data-cy=comment]')
      .type('Great blog!')
    cy.get('[data-cy=submitComment]')
      .click()
    cy.contains('Great blog!')
    
  })

  it('like button click increments likes', function () {
    cy.get('[data-cy=username]')
      .type('joonaskinnunen')
    cy.get('[data-cy=password]')
      .type('password')
    cy.get('[data-cy=login]')
      .click()
    cy.contains('Joonas Kinnunen logged in')
    cy.contains('create new')
      .click()
    cy.get('[data-cy=title]')
      .type('New Blog')
    cy.get('[data-cy=author]')
      .type('Joonas Kinnunen')
    cy.get('[data-cy=url]')
      .type('http://newblogurl.com')  
    cy.get('[data-cy=newBlog]')
      .click()
    cy.contains('New Blog Joonas Kinnunen')
      .click({ force: true })
    cy.get('[data-cy=like]')
      .click()
    cy.contains('1 likes')
    cy.get('[data-cy=like]')
      .click()
    cy.contains('2 likes')
    
  })

  it('wrong log in credentials shows error notification', function () {
    cy.get('[data-cy=username]')
      .type('joonaskinnunen')
    cy.get('[data-cy=password]')
      .type('wrongpassword')
    cy.get('[data-cy=login]')
      .click()
    cy.contains('wrong username of password')
  })

  it('logout works', function () {
    cy.get('[data-cy=username]')
      .type('joonaskinnunen')
    cy.get('[data-cy=password]')
      .type('password')
    cy.get('[data-cy=login]')
      .click()
    cy.get('[data-cy=logout]')
      .click()
    cy.contains('log in to application')
  })

})